README.md, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/StringUtils.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/TomlParser.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlArrayOfTables.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlInlineTable.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlKeyValue.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlTablePrimitive.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/ReadMeExampleTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/parsers/CommentsParsing.kt
- removed debug pretty print from the code
- fixed the logic for inline comments with tables
=> Hotfixes for the release

ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlValue.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/utils/Utils.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/parsers/ValueParserTest.kt, ktoml-core/src/jsMain/kotlin/com/akuleshov7/ktoml/utils/UtilsJs.kt, ktoml-core/src/jvmMain/kotlin/com/akuleshov7/ktoml/utils/UtilsJvm.kt, ktoml-core/src/linuxX64Main/kotlin/com/akuleshov7/ktoml/utils/UtilsLinux.kt, ktoml-core/src/macosX64Main/kotlin/com/akuleshov7/ktoml/utils/UtilsMac.kt, ktoml-core/src/mingwX64Main/kotlin/com/akuleshov7/ktoml/utils/UtilsWin.kt
=> Support unicode symbols in strings

ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/annotations/TomlComments.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/annotations/TomlInlineTable.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/annotations/TomlInteger.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/annotations/TomlLiteral.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/annotations/TomlMultiline.kt
I've added the annotations suggested in #114, as well as a few more I thought would be desired: `TomlInlineTable`, `TomlInteger`, and `TomlMultiline`
=> Add serialization annotations

README.md, buildSrc/src/main/kotlin/com/akuleshov7/Versions.kt, buildSrc/src/main/kotlin/com/akuleshov7/buildutils/PublishingConfiguration.kt, gradle.properties, ktoml-core/build.gradle.kts, ktoml-core/src/iosMain/kotlin/com/akuleshov7/ktoml/utils/UtilsIos.kt, ktoml-core/src/macosArm64Main/kotlin/com/akuleshov7/ktoml/utils/UtilsMacM1.kt, ktoml-file/build.gradle.kts, ktoml-file/src/iosMain/kotlin/com/akuleshov7/ktoml/file/FileUtilsIos.kt, ktoml-file/src/macosArm64Main/kotlin/com/akuleshov7/ktoml/file/FileUtilsMacM1.kt
Adds an iOS meta target,
I'm not sure if there is more to be done on the publishing side? But this compiles for me.
=> Add Ios target

README.md
=> Add README encoding examples

ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/StringUtils.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/TomlParser.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/pairs/TomlKeyValue.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/tables/TomlArrayOfTables.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/tables/TomlTablePrimitive.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/parsers/StringUtilsTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/parsers/ValueParserTest.kt
=> Fix bug with inline comment

README.md, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/TomlParser.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/ArrayDecoderTest.kt
Fix #126
Hello! And thanks for your library! I love Kotlin and I like KTOML format. But I have never done any parsers before. So, I hope you will be patient with me :)
My idea is to merge multiline values into a single line and then process it as usually. If I missed something or this code needs improvement - I am ready.
=> Handle multi-line array

ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/StringUtils.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/pairs/values/TomlArray.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/ArrayDecoderTest.kt
=> Handle trailing comma in array

README.md, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlAbstractDecoder.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/encoders/TomlAbstractEncoder.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/GeneralDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/PrimitivesDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/encoders/PrimitiveEncoderTest.kt
A quick stab at showing how non-Long numbers could be encoded and decoded. 
#163 
This is a very quick draft, I haven't spent a lot of time on it. I'm just sharing because I think the general approach is good.
This approach is based off the Kotlinx Serialization approach to handling JSON numbers
https://github.com/Kotlin/kotlinx.serialization/blob/dc950f5098162a3f8dd742d04b95f9a0405470e1/formats/json/commonMain/src/kotlinx/serialization/json/internal/StreamingJsonDecoder.kt#L281-L290
First the numbers are parsed as a Long or Double, as is already the case. Then ktoml will try to manually convert these numbers to the required type, but first verifying that the numbers are in range.
If you wanted to verify based on the raw string content, you could perhaps implement a function based on how …
=> quick POC at non-Long numerics (encoding and decoding)

ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlAbstractDecoder.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/utils/Types.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/PrimitivesDecoderTest.kt
- enabled the decoding of Float type
=> Removing a Double restriction: float support

ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlAbstractDecoder.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMainDecoder.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/StringUtils.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/utils/Types.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/ArrayDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/ArrayOfTablesDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/CharDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/CustomSerializerTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/DottedKeysDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/GeneralDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/IntegersDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/PrimitivesDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/ReadMeExampleTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/SurrogateSerializerTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/encoders/TomlDocsEncoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/parsers/TomlTableTest.kt
- conversion from string to char
- enabling some old tests
- still we need unicode conversion
=> Adding the support for Char

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/com/akuleshov7/Versions.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/pairs/values/TomlBasicString.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/CharDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/CustomSerializerTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/IntegersDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/StringsDecoderTest.kt
- test for literal strings
- migration to Kotlin 1.8
=> Migration to a new 1.8 Kotlin

README.md, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlAbstractDecoder.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/exceptions/TomlDecodingException.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/pairs/values/TomlBasicString.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/utils/SpecialCharacters.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/writers/TomlEmitter.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/CharDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/IntegersDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/ReadMeExampleTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/StringsDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/parsers/StringUtilsTest.kt, ktoml-file/src/commonTest/resources/simple_example.toml
- Previously ktoml did not support special escaped characters while decoding of Char type
- Added extra tests for literal strings
- Moved logic related to the escaped characters to new utils file
=> Support for special symbols with Char type

ktoml-core/build.gradle.kts, ktoml-file/build.gradle.kts
Allows to use ktoml (at runtime) on older JVMs. Since Kotlin currently targets 1.8 IL, there's zero difference at compile or test time.
=> Lower JVM target to 1.8

ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/tables/TomlTable.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/encoders/ArrayEncoderTest.kt
Fixes #226 TomlTable.write() throws NoSuchElementExceptionthrows NoSuchElementException if children is empty
=> Fixes #226 TomlTable.write() throws NoSuchElementException

ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/exceptions/TomlDecodingException.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/utils/Utils.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/EnumValidationTest.kt
- Inspired by Diktat: in most configuration files, we use enums, and authors of libraries working with these configuration files would like to assist users in identifying any misprints and suggesting the closest valid values
- Actually I believe that this functionality should be implemented in all decoding libraries
=> Levenshtein distance calculation for the enhancement of the 'invalid enum' error

ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/encoders/TomlAbstractEncoder.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/encoders/ValueClassEncoderTest.kt
Fix #237 
Please read the test cases carefully. I took some of them from [docs](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/value-classes.md). We shouldn't handle value classes as data classes, so I wrote encoding looking at Json serializer.
=> Add encoding value classes

ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/tables/TomlInlineTable.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/InlineTableDecoderTest.kt
=> Add support for empty inline table

README.md, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlArrayDecoder.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMainDecoder.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMapDecoder.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/exceptions/TomlDecodingException.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/PlainMapDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/ReadMeExampleTest.kt
- Phaze 1: only primitive tables (without nested multiple tables) with no explicit  type checking.
- The idea is to decode unnamed arguments.
For example: 
```
[map]
a = 1
b = 2 
```
or 
```
map = {a=1, b=2}
```
Should be decoded (without knowing and naming explicitly toml keys) to:
```
data class Test {
val map: Map<String, Int>
}
```
Guys like @jakubgwozdz @y9san9 requested it and it looks like it can be useful for parsing gradle configs.
=> Initial Support for Simple Map decoding with unnamed toml keys

README.md, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMainDecoder.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMapDecoder.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/NestedMapTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/NestedTableTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/PlainMapDecoderTest.kt
- Added a support for nested anonymous Maps
=> Support for nested and inlined maps (inside other maps)

ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/encoders/TomlAbstractEncoder.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/encoders/PrimitiveEncoderTest.kt
- As per the TOML specification, there is no predefined Char type. However, we've introduced the concept in our TOML implementation to align more closely with Kotlin's syntax. So we are expecting Chars to have single quote on the decoding. We need to make it more convenient and do encoding and decoding in a similar way.
=> Primitive Char should be encoded with a single quote

.github/workflows/build_and_test.yml, .github/workflows/detekt.yml, .github/workflows/diktat.yml, .github/workflows/release.yml, buildSrc/build.gradle.kts, settings.gradle.kts
- updated reckon 
- updated grgit
=> Updating problematic versions of ajoberstar repos

ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/StringUtils.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/pairs/TomlKeyValue.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/pairs/keys/TomlKey.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/keys/DottedKeysDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/keys/QuotedKeysDecoderTest.kt
Fixes #235
- Removed extra `trimQuotes()` in `String.validateSymbols()` to allow special symbols in quoted keys #235
- Added `trimSingleQuotes()` in `TomlKey.last()` to fix [this](https://github.com/orchestr7/ktoml/issues/235#issuecomment-2081630668) 
- Renamed `String.getCommentStartIndex` to `String.indexOfFirstOutsideQuotes` and extended it's usage to search for any symbol, which allows to use '=' in quoted keys
- Added extra `.trim()` in `String.splitKeyToTokens` to fit the following requirements:
=> Fix quoted and dotted keys

README.md, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/StringUtils.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/pairs/TomlKeyValue.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/tables/TomlInlineTable.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/InlineTableDecoderTest.kt
Fixes #107
- Support Nested Inline Tables
- Support arrays in inline tables
First problem was in `TomlInlineTable::parseInlineTableValue`, when we called `.split(",")`. It doesn't work with arrays (cause they also have comma) and with nested inline tables. Now we do the same split, but ignore all commas inside arrays/nested inline.
Second problem was in `TomlInlineTable::returnTable`, in test case we had this TomlTable fullTableKey:
=> Support Nested Inline Tables

README.md, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlAbstractDecoder.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlArrayDecoder.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/pairs/TomlKeyValue.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/pairs/values/TomlUnsignedLong.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/utils/SpecialCharacters.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/utils/Types.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/writers/TomlEmitter.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/UnsignedNumbersDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/encoders/EncodingAnnotationTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/writers/ValueWriteTest.kt
Fixes #173 
> Neither signed, nor unsigned integers are subtypes of each other.
So there's a bit of code duplication in parsing and serialization between unsigned types and integers, but nothing crucial
=> Support unsigned integers

README.md, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlArrayOfTablesDecoder.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMainDecoder.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/ArrayOfTablesDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/encoders/TomlDocsEncoderTest.kt
Fixes #88 , Fixes #231  - Finally :)
Added tests with examples from:
- Documentation
- #231
- #254 
#259 isn't implemented yet, because it's an inline array of tables (#99)
=> Implement decoding for array of tables

ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/tables/TomlTable.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/writers/TableWriteTest.kt
Fixed an issue where nested tables (e.g., [a.b], [a.c]) under an empty parent table (e.g., [a]) were omitted during serialization, leading to missing configuration data. This fix ensures that nested tables are properly serialized, even when their parent tables are empty.
#309
=> Fix serialization of nested tables under empty parent tables

README.md
I just looked up, and it's already supported, except for array of inline tables: #315
=> Show in README that encoding for inline array of table is supported

ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/StringUtils.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/TomlMultilineString.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/multiline/BasicMultilineStringDecoderTest.kt
I had some pre-existing `.toml` files which embedded markdown, and these managed to trip up this parser. I managed to track down what caused the crashes and included some minimal reproductions as test cases. Before the included fixes these tests would fail, but they now pass.
In the below example the parser would not detect the multiline string as closing, since it required a line ending with `"""`.
```toml
a = """
Multiple lines are required to trigger this bug, triple-quotes are not enough
""" # A comment placed here causes a crash
```
In the below example the parser successfully finds the extent of the mutli-line string, but crashes when splitting the key and value. This happened because the pair is first processed via `takeBeforeComment`, which incorrectly found the markdown header …
=> Fixes around comments in/around multiline strings

ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/pairs/TomlKeyValue.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/tables/ArrayOfTablesDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/parsers/ArraysOfTablesTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/parsers/TomlTableTest.kt
Previously, the parser would produce the wrong tree structure for use of `dotted.key = "value"` while inside of an `[[arrayOfTables]]`. As an example:
```toml
[[arrayOfTables]]
dotted.key = "value"
```
Before this fix, this is parsed as:
```
- TomlFile (rootNode)
- TomlTable ([[arrayOfTables]])
- TomlArrayOfTablesElement (technical_node)
- TomlTable ([dotted])
- TomlKeyValuePrimitive (key="value")
```
After this fix, it is now correctly parsed as:
```
- TomlFile (rootNode)
- TomlTable ([[arrayOfTables]])
- TomlArrayOfTablesElement (technical_node)
- TomlTable ([arrayOfTables.dotted])
- TomlKeyValuePrimitive (key="value")
```
This matches the structure that was already working when using a non-array table:
```toml
[table]
dotted.key = "value"
```
```
- TomlFile (rootNode)
- TomlTable …
```
=> Fix parsing of dotted keys inside array-of-tables

buildSrc/build.gradle.kts, buildSrc/src/main/kotlin/com/akuleshov7/Versions.kt, ktoml-core/build.gradle.kts, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlAbstractDecoder.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/encoders/TomlAbstractEncoder.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/pairs/values/TomlDateTime.kt, ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/writers/TomlEmitter.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/primitives/DateTimeDecoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/encoders/DateTimeEncoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/encoders/TomlDocsEncoderTest.kt, ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/writers/ValueWriteTest.kt, ktoml-core/src/macosX64Main/kotlin/com/akuleshov7/ktoml/utils/UtilsMac.kt, ktoml-core/src/mingwX64Main/kotlin/com/akuleshov7/ktoml/utils/UtilsWin.kt, ktoml-file/build.gradle.kts, ktoml-source/build.gradle.kts
- Reworked kotlin.time.Instant usages to a new API
- Updated minor versions, especially org.jetbrains.kotlinx:kotlinx-datetime:0.7.1-0.6.x-compat
=> Update all non-major dependencies (except core Kotlin)
