- src/ktomlMain/kotlin/com/akuleshov7/ktoml/Ktoml.kt
- src/ktomlMain/kotlin/com/akuleshov7/ktoml/decoders/DecoderConf.kt
- src/ktomlMain/kotlin/com/akuleshov7/ktoml/decoders/SerializationConf.kt
- src/ktomlMain/kotlin/com/akuleshov7/ktoml/decoders/TomlDecoder.kt
- src/ktomlMain/kotlin/com/akuleshov7/ktoml/exceptions/Exceptions.kt
- src/ktomlMain/kotlin/com/akuleshov7/ktoml/parsers/node/TomlNode.kt
- src/ktomlTest/kotlin/decoder/DecoderTest.kt
- src/ktomlTest/kotlin/node/parser/TomlNodeTest.kt
> Missing required fields support

- .git-hooks/commit-msg.sh
- .git-hooks/pre-commit.sh
- README.md
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/com.akuleshov7/buildutils/DiktatConfiguration.kt
- added git hooks
- small corrections
> Adding git-hooks

- README.md
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/node/TomlNode.kt
- ktoml-core/src/commonTest/kotlin/node/parser/ValueParserTest.kt
- fixed a bug when comments were ignore very lately
> Fixing commenting bug

- README.md
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/Ktoml.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/KtomlConf.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/Toml.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/DecoderConf.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlDecoder.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlListDecoder.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/ParserConf.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/TomlParser.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/node/TomlKeyValue.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/node/TomlValue.kt
- ktoml-core/src/commonTest/kotlin/decoder/ArrayDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/decoder/DottedKeysDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/decoder/GeneralDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/decoder/PartialDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/decoder/ReadMeExampleTest.kt
- ktoml-core/src/commonTest/kotlin/file/TomlFileParserTest.kt
- ktoml-core/src/commonTest/kotlin/node/parser/ValueParserTest.kt
- Changed the API and public API names
- Fixed bugs related to Array parsing
- Changed the decoding logic: beginStructure
- Updated the readme and added more test examples
> Cosmetic preparations and bug-fixing before the 0.2.6 release

- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlDecoder.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/StringUtils.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/node/TomlKey.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/node/TomlKeyValue.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/node/TomlNode.kt
- ktoml-core/src/commonTest/kotlin/decoder/GeneralDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/node/parser/DottedKeyParserTest.kt
> Fix for an issue with comments and string values

- README.md
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlDecoder.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/exceptions/Exceptions.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/node/TomlKeyValue.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/node/TomlValue.kt
- ktoml-core/src/commonTest/kotlin/decoder/ArrayDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/decoder/DecodingTypeTest.kt
- ktoml-core/src/commonTest/kotlin/decoder/DottedKeysDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/decoder/GeneralDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/decoder/PartialDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/decoder/ReadMeExampleTest.kt
- ktoml-core/src/commonTest/kotlin/file/TomlFileParserTest.kt
- ktoml-core/src/commonTest/kotlin/node/parser/ValueParserTest.kt
Improving logging that can appear when the user uses incorrect type for deserialization.
> Improving logging: adding proper logging for exceptions 

- README.md
Updated the version of ktoml in the readme: 0.2.8 -> 0.2.9
> Updating the readme after the release

- README.md
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/TomlConfig.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMainDecoder.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlNode.kt
- ktoml-core/src/commonTest/kotlin/com/akulashov7/ktoml/decoders/NullableTablesTest.kt
- Adding the support for empty TOML
- Adding new configuration allowEmptyToml
> Adding the support for empty TOML

- .github/workflows/detekt.yml
- .github/workflows/diktat.yml
- README.md
- diktat action updated
- detekt action updated
> Fixing CI/CD for diktat and detekt

- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/Toml.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlNode.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/utils/Utils.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/NullableTablesTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/PartialDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/parsers/ArraysOfTablesTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/parsers/TableFinder.kt
- ktoml-file/src/commonTest/kotlin/com/akuleshov7/ktoml/file/TomlFileParserTest.kt
- fixed partial decoding
- updated tests
> Fixing the partial decoding mechanism

- .github/workflows/diktat.yml
- buildSrc/build.gradle.kts
- buildSrc/src/main/kotlin/com/akuleshov7/buildutils/DiktatConfiguration.kt
> Updating diktat version and corresponding action, adding the integration with github

- README.md
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/TomlConfig.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlKeyValue.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/GeneralDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/parsers/ValueParserTest.kt
> Allow disabling of null handling

- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlValue.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/ArrayDecoderTest.kt
- ktoml-core/src/jsMain/kotlin/com/akuleshov7/ktoml/utils/UtilsJs.kt
> Handle commas in string for arrays.

- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/TomlConfig.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlArrayDecoder.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/StringUtils.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/TomlParser.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlArrayOfTables.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlFile.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlInlineTable.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlKeyValue.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlKeyValueArray.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlKeyValuePrimitive.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlNode.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlStubEmptyNode.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlTable.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/TomlTablePrimitive.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/writers/TomlEmitter.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/parsers/CommentsParsing.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/parsers/ValueParserTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/writers/CommentWriteTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/writers/KeyValueWriteTest.kt
> Store comments in the tree

- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/writers/TomlEmitter.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/encoders/PrimitiveEncoderTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/encoders/TomlDocsEncoderTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/writers/ValueWriteTest.kt
> Fix Double encoding on JS

- README.md
- ktoml-core/build.gradle.kts
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlAbstractDecoder.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/encoders/TomlAbstractEncoder.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/pairs/values/TomlDateTime.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/writers/TomlEmitter.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/DateTimeDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/encoders/DateTimeEncoderTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/writers/ValueWriteTest.kt
> Support LocalTime

- README.md
- ktoml-file/build.gradle.kts
- ktoml-file/src/iosSimulatorArm64Main/kotlin/com/akuleshov7/ktoml/file/FileUtilsIosSimulator.kt
- added iosSimulatorArm64 to ktoml-file
- changed ktoml-source dependency to api() to reduce dependency complexity
> Infra and build updates

- README.md
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlArrayDecoder.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/StringUtils.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/TomlMultilineString.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/TomlParser.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/enums/MultilineType.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/pairs/values/TomlArray.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/utils/LinesIteratorWrapper.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/ArrayDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/multiline/ArrayOfStringsDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/multiline/MultilineArrayTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/parsers/CommonParserTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/parsers/SetLineNoTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/parsers/StringUtilsTest.kt
- Support decoding nested arrays
- Support decoding arrays of multiline strings
- Refactor multiline values parsing
- Fix incorrect parsing toml with `' " ] [` inside string which is an element of array
> Support decoding nested arrays and arrays of multiline strings

- README.md
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/TomlConfig.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMainDecoder.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/GeneralDecoderTest.kt
> Prohibit default values with a special option

- README.md
The README was outdated, so I bumped the versions to the latest release version
> bump version: 0.5.1 --> 0.5.2

- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/Toml.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMainDecoder.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMapDecoder.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/NestedMapTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/PlainMapDecoderTest.kt
> Fix decoding map

- README.md
- ktoml-core/build.gradle.kts
- ktoml-core/src/wasmJsMain/kotlin/com/akuleshov7/ktoml/utils/UtilsWasmJs.kt
- ktoml-core/src/wasmWasiMain/kotlin/com/akuleshov7/ktoml/utils/UtilsWasmWasi.kt
- ktoml-file/build.gradle.kts
- ktoml-source/build.gradle.kts
> Adding new build targets: WasmJs/WasmWasi

- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMapDecoder.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/MapDecoderTest.kt
> Support map of objects decoding

- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlAbstractDecoder.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/UnsignedNumbersDecoderTest.kt
> Add validation for unsigned numbers

- README.md
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/StringUtils.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/TomlParser.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/tree/nodes/tables/TomlInlineTable.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/ArrayOfTablesDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/InlineArrayOfTableDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/InlineTableDecoderTest.kt
> Implement decoding for inline array of tables

- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/decoders/TomlMainDecoder.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/ArrayDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/MapDecoderTest.kt
> Add specific error for wrong type when array/map is expected

- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/encoders/TomlAbstractEncoder.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/encoders/TomlEncoderAttributes.kt
- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/exceptions/TomlEncodingException.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/ArrayOfTablesDecoderTest.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/encoders/ArrayOfTablesEncoderTest.kt
- Improved error handling: previously, users encountered vague "Internal error" messages. These have been replaced with clear logging and meaningful exceptions to improve debugging and transparency.
- Significantly expanded test coverage to ensure more robust and reliable behavior.
> Enhancing Encoding Logs and Error Handling for Arrays of Tables

- ktoml-core/src/commonMain/kotlin/com/akuleshov7/ktoml/parsers/TomlMultilineString.kt
- ktoml-core/src/commonTest/kotlin/com/akuleshov7/ktoml/decoders/multiline/MultilineArrayTest.kt
> Allow trailing comma in multiline nested arrays
